// Plain data file — no path aliases, safe to import from next.config.ts
export const READER_SLUG_REDIRECTS: { key: string; slug: string }[] = [
  { key: "adele-3622", slug: "adele-psychic" },
  { key: "aelissa-4444", slug: "aelissa-psychic" },
  { key: "alice-6543", slug: "alice-psychic" },
  { key: "andy-3399", slug: "andy-psychic" },
  { key: "angel-1441", slug: "angel-psychic" },
  { key: "bryony-2727", slug: "bryony-psychic" },
  { key: "daisy-6006", slug: "daisy-psychic" },
  { key: "ellie-1180", slug: "ellie-psychic" },
  { key: "fran-1133", slug: "fran-psychic" },
  { key: "jasmine-5115", slug: "jasmine-psychic" },
  { key: "joanna-4567", slug: "joanna-psychic" },
  { key: "john-5152", slug: "john-psychic" },
  { key: "julien-4334", slug: "julien-psychic" },
  { key: "karen-5791", slug: "karen-psychic" },
  { key: "mariah-1881", slug: "mariah-psychic" },
  { key: "mary-5055", slug: "mary-psychic" },
  { key: "mavis-1010", slug: "mavis-psychic" },
  { key: "pauline-3798", slug: "pauline-psychic" },
  { key: "robbie-3443", slug: "robbie-psychic" },
  { key: "ruth-2022", slug: "ruth-psychic" },
  { key: "sandra-2662", slug: "sandra-psychic" },
  { key: "sarah-9888", slug: "sarah-psychic" },
  { key: "toby-2333", slug: "toby-psychic" },
];
